source: _dist

# Site settings
title: Vince Golveo
email: vince.golveo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Frontend Engineer - Artist - Applications Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vincegolveo.com/" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: binzu
github_username:  binzu
# facebook_username: StartBootstrap
#instagram_username:
#stackoverflow_url: https://
#googleplus_username:
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/vincegolveo/

# Address information
address_street: Bedford-Stuyvesant
address_city: Brooklyn
address_state: NY
address_zip: 11238

# Build settings
markdown: kramdown
