# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vince Golveo
email: vince.golveo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front-End Web Developer Consultant
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vincegolveo.com/" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: binzu
github_username:  binzu
# facebook_username: StartBootstrap
#instagram_username:
#stackoverflow_url: https://
#googleplus_username:
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/vincegolveo/

# Address information
address_street: Bedford-Stuyvesant
address_city: Brooklyn
address_state: NY
address_zip: 11238

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman